### ISSUE TITLE
Translation of translator

### ISSUE THREAD

**Issue by espensj** [dohliam/gasp-translator#10]
I think we should go with a translation of the word "translator", otherwise it will break with the flow, and it looks awkward with an English word on the page. It's not like we're translating "Facebook" into Ansiktsbok". (Although some people actually call it "Fjesboka"! :)

**Comment by dohliam** [comment]
Makes sense.

In terms of capitalization, I know book titles etc generally only capitalize the first word in Norwegian, whereas [newspapers](https://no.wikipedia.org/wiki/Liste_over_norske_aviser) and [companies](https://no.wikipedia.org/wiki/Liste_over_Norges_500_st%C3%B8rste_selskaper_i_2006) usually have each word of their name capitalized.

What about in this case? Should "oversetter" be capitalized or not? It looks a bit odd to me in lowercase but I'm not sure what the convention would be.

**Comment by espensj** [comment]
Jeg viste faktisk ikke at aviser og bedrifter bruker store bokstaver!
Titler og bøker bruker ikke det. Så liten bokstav. Se her:
https://no.wikipedia.org/wiki/Jens_Bj%C3%B8rneboe#Bibliografi

E

**Comment by dohliam** [comment]
Fixed!
