### ISSUE TITLE
Cache on Translator saved across languages

### ISSUE THREAD

**Issue by espensj** [dohliam/gasp-translator#11]
I translated a story from English into Norwegian, and now the same story appears in the cache (or whatever) in my browser when I translate using the Norwegian translator, which makes no sense. The browser cache should be cleared for a new language.

![screen shot 2015-10-17 at 11 08 17 am](https://cloud.githubusercontent.com/assets/12679303/10560409/66ea50ca-74bf-11e5-968a-aad2e14068cf.png)

**Comment by dohliam** [comment]
Thanks for pointing this out. You're right that the different versions should use different storage/cache.

In any case, I can fix this, but it will wipe out any current translations you have in the Norwegian translator. Is that ok?

**Comment by espensj** [comment]
Yes, go ahead. Thanks.

**Comment by dohliam** [comment]
Done. Let me know if everything is ok now and I will close this issue.

**Comment by espensj** [comment]
Yes, it works now.
