### ISSUE TITLE
Random story button needs fixing in Norwegian translator

### ISSUE THREAD

**Issue by espensj** [dohliam/gasp-translator#12]
The random story button ![screen shot 2015-10-17 at 11 10 15 am](https://cloud.githubusercontent.com/assets/12679303/10560422/a97b9746-74bf-11e5-987f-106f141f4321.png) seems to render any of the 364 stories, but only 19 of them exist in Norwegian, so 80% of the time the button doesn't work. In other words I have to click 4–5 times to get a new story.

**Comment by dohliam** [comment]
That is certainly no good! I'll fix it ASAP.

**Comment by dohliam** [comment]
Fixed. Please test to make sure everything is working.

**Comment by espensj** [comment]
Perfekt!
