### ISSUE TITLE
Skip translated stories

### ISSUE THREAD

**Issue by dohliam** [dohliam/gasp-translator#16]
Moved from [here](https://github.com/global-asp/global-asp/issues/10):

> I would like to see a button/link for skipping translated stories. I have to flip through 10 stories in Norwegian to get to the first that has not already been translated. Something like this:
> 
> ![screen shot 2016-01-17 at 11 46 51 am](https://cloud.githubusercontent.com/assets/12679303/12379487/b6d18826-bd10-11e5-93a5-178dd13c8a06.png)

**Comment by espensj** [comment]
It doesn't actually work, it just skips the current story.

**Comment by dohliam** [comment]
It seems to work here -- when the language is set to `norsk` the "Skip translated stories button" takes me directly to story #0049 (which has not yet been translated). If I just go to the next story in sequence (i.e. using the "next story" button), it takes me to #0127, which has already been translated into Norwegian.

What browser are you using? Have you tried reloading / clearing the cache?

**Comment by espensj** [comment]
Chrome og Safari. Samme problem, også når jeg går inkognito, så da er det
vel ikke cachen. Jeg har ikke brukt Translator i Safari før – jeg bruker
aldri den nettleseren.

E

**Comment by dohliam** [comment]
Can you try it on a different machine running OSX? (Just to eliminate the possibility that it has something to do with your machine.) I'm still getting the expected behaviour here after trying it on several different machines and browsers.

**Comment by dohliam** [comment]
Had someone try this on a iPad and can confirm it works fine on Safari for iOS...

**Comment by espensj** [comment]
Jeg prøvde på Tanvis maskin, det funka ikke. Vi kan se på det i morgen når
vi treffes.

E

**Comment by dohliam** [comment]
Strange -- sounds like it could be an OSX issue? Android, iOS, Linux all work fine.

**Comment by mapmeld** [comment]
Can you describe what is happening on your machine? Maybe you're still loading the cached version?

**Comment by dohliam** [comment]
After some investigation, I think I understand what is happening. @espensj is in fact seeing the expected behaviour, but thought that pressing "Skip translated stories" would skip _all_ translated stories, i.e. would only need to be pressed once.

I can see where this would be incovenient for the Norwegian translations specifically, because the existing translations are not necessarily in sequence, so the "skip" button needs to be pressed multiple times while browsing for a new story to translate.

I think we might be able to modify the "skip" button slightly to make it a "show/hide translated stories" toggle. There's actually lots of space for a new icon in the menubar now, since 6cef519 makes the "Permalink" button unnecessary.

**Comment by dohliam** [comment]
I've opened [a new issue](https://github.com/dohliam/gasp-translator/issues/19) to track progress on this, since I think it's a substantially different feature request (though we can adapt the "Skip translated stories" button for this purpose).
