### ISSUE TITLE
Wide spacing in "List of ASP stories that have translations"

### ISSUE THREAD

**Issue by espensj** [dohliam/gasp-translator#21]
The licence (CC-BY-NC) in the list of ASP stories that have translations has runs over two or three lines, giving a lot of white space. Can we force this column to be wide enough to have space for "CC-BY-NC" on one line? 
![screen shot 2016-05-04 at 11 04 56 am](https://cloud.githubusercontent.com/assets/12679303/15024139/754b8974-11e8-11e6-85c1-9f3a7c2102b9.png)

**Comment by dohliam** [comment]
I'll try to clean this up along with the layout on the rest of the page.

**Comment by dohliam** [comment]
Fixed in latest update.
