### ISSUE TITLE
Review submission window should be larger

### ISSUE THREAD

**Issue by dohliam** [dohliam/gasp-translator#3]
It would be nice to have a somewhat larger window for reviewing the translation. How large it should be specifically remains an open question...

**Comment by dohliam** [comment]
Suggested height is 90%

**Comment by dohliam** [comment]
@espensj: The window has now been resized to 95% in the Norwegian version of gasp-translator. Can you check that this is an improvement and if so we can implement it in the main version.

**Comment by espensj** [comment]
This looks great, thanks. But I wouldn't mind widening the window slightly. For short stories it doesn't matter much, but for longer ones it reads a bit better, I think. Look at this muck-up.

![screen shot 2015-10-17 at 10 54 41 am](https://cloud.githubusercontent.com/assets/12679303/10560339/a01a12f6-74bd-11e5-89a5-9ad525fc312c.png)

But it's not a priority, of course.

**Comment by dohliam** [comment]
Ok, that's easy to fix. How wide exactly would you like the window to be (as a percentage of the screen)? It's currently at 50%.

**Comment by espensj** [comment]
I think 75% should do. Thanks.

**Comment by dohliam** [comment]
Changed to 75%. Let me know if this is sufficient.

**Comment by espensj** [comment]
This looks great, thanks. Like I said it matters more for long stories.

![screen shot 2015-10-17 at 1 13 22 pm](https://cloud.githubusercontent.com/assets/12679303/10560991/e9414c16-74d0-11e5-9411-271955de21c0.png)
