### ISSUE TITLE
Store email address in localStorage

### ISSUE THREAD

**Issue by dohliam** [dohliam/gasp-translator#5]
Some translators have complained about having to (optionally) fill in their email address each time they submit a story, since the value of the email field is not currently stored. This can be fixed by auto-updating the field in get_storage().

**Comment by dohliam** [comment]
@espensj: Can you test this to make sure it works on your end?

**Comment by espensj** [comment]
What am I supposed to test?

**Comment by dohliam** [comment]
@espensj Test whether it stores your email address so you don't have to type it out every time.

**Comment by espensj** [comment]
Do you mean whether my email appears? I didn't in the first story, but in
the second one. SO I guess that's a 'yes'

E

**Comment by espensj** [comment]
"unable to submit form"

Det funka i går kveld!

E

**Comment by dohliam** [comment]
!?

Er det kanskje en adblocker du har på maskinen din? Du kan prøv å
deaktivere den på siden.

L
